[2021-03-12 07:42:51,461] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskSchemaConv 2021-03-12T07:42:46+00:00 [queued]>
[2021-03-12 07:42:51,472] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskSchemaConv 2021-03-12T07:42:46+00:00 [queued]>
[2021-03-12 07:42:51,472] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 07:42:51,473] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-12 07:42:51,473] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 07:42:51,486] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): taskSchemaConv> on 2021-03-12T07:42:46+00:00
[2021-03-12 07:42:51,488] {standard_task_runner.py:52} INFO - Started process 4218 to run task
[2021-03-12 07:42:51,491] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'conversion_flow', 'taskSchemaConv', '2021-03-12T07:42:46+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', '/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py', '--cfg-path', '/tmp/tmp_m5242sh', '--error-file', '/tmp/tmpiorqsh1e']
[2021-03-12 07:42:51,492] {standard_task_runner.py:77} INFO - Job 18: Subtask taskSchemaConv
[2021-03-12 07:42:51,520] {logging_mixin.py:104} INFO - Running <TaskInstance: conversion_flow.taskSchemaConv 2021-03-12T07:42:46+00:00 [running]> on host 83c843b036e0
[2021-03-12 07:42:51,543] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=conversion_flow
AIRFLOW_CTX_TASK_ID=taskSchemaConv
AIRFLOW_CTX_EXECUTION_DATE=2021-03-12T07:42:46+00:00
AIRFLOW_CTX_DAG_RUN_ID=conversion_flow1615534966.845451
[2021-03-12 07:42:51,597] {logging_mixin.py:104} INFO - Error while dropping MongoDB database sakila! Re-check connection or name of database.
[2021-03-12 07:42:51,597] {logging_mixin.py:104} INFO - port must be an instance of int
[2021-03-12 07:42:51,597] {conversion_flow.py:113} ERROR - Error Occure in taskDataConv Task!
[2021-03-12 07:42:51,597] {conversion_flow.py:114} ERROR - port must be an instance of int
[2021-03-12 07:42:51,597] {taskinstance.py:1455} ERROR - port must be an instance of int
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 115, in taskSchemaConv
    raise exception
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 103, in taskSchemaConv
    schema_conversion.run()
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/schema_conversion.py", line 35, in run
    self.__drop_mongodb()
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/schema_conversion.py", line 100, in __drop_mongodb
    drop_mongodb_database(self.schema_conv_output_option)
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/utilities.py", line 90, in drop_mongodb_database
    raise e
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/utilities.py", line 84, in drop_mongodb_database
    mongo_client = MongoClient(connection_string,schema_conv_output_option.username,schema_conv_output_option.password)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 614, in __init__
    raise TypeError("port must be an instance of int")
TypeError: port must be an instance of int
[2021-03-12 07:42:51,599] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=conversion_flow, task_id=taskSchemaConv, execution_date=20210312T074246, start_date=20210312T074251, end_date=20210312T074251
[2021-03-12 07:42:51,623] {local_task_job.py:146} INFO - Task exited with return code 1
