[2021-03-12 04:07:58,980] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-10T12:00:00+00:00 [queued]>
[2021-03-12 04:07:58,992] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-10T12:00:00+00:00 [queued]>
[2021-03-12 04:07:58,992] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 04:07:58,992] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-12 04:07:58,992] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 04:07:59,001] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): taskPrepare> on 2021-03-10T12:00:00+00:00
[2021-03-12 04:07:59,003] {standard_task_runner.py:52} INFO - Started process 1371 to run task
[2021-03-12 04:07:59,013] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'conversion_flow', 'taskPrepare', '2021-03-10T12:00:00+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', '/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py', '--cfg-path', '/tmp/tmptsfujvon', '--error-file', '/tmp/tmpllmkvbg2']
[2021-03-12 04:07:59,014] {standard_task_runner.py:77} INFO - Job 2: Subtask taskPrepare
[2021-03-12 04:07:59,047] {logging_mixin.py:104} INFO - Running <TaskInstance: conversion_flow.taskPrepare 2021-03-10T12:00:00+00:00 [running]> on host 83c843b036e0
[2021-03-12 04:07:59,080] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=conversion_flow
AIRFLOW_CTX_TASK_ID=taskPrepare
AIRFLOW_CTX_EXECUTION_DATE=2021-03-10T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-10T12:00:00+00:00
[2021-03-12 04:07:59,080] {conversion_flow.py:73} ERROR - Error Occure in taskPrepare Task!
[2021-03-12 04:07:59,080] {conversion_flow.py:74} ERROR - 'NoneType' object has no attribute 'split'
[2021-03-12 04:07:59,080] {taskinstance.py:1455} ERROR - 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 75, in taskPrepare
    raise exception
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 29, in taskPrepare
    if sql_file_name.split(".")[1] != "sql":
AttributeError: 'NoneType' object has no attribute 'split'
[2021-03-12 04:07:59,081] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=conversion_flow, task_id=taskPrepare, execution_date=20210310T120000, start_date=20210312T040758, end_date=20210312T040759
[2021-03-12 04:07:59,100] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-03-12 08:50:16,493] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-10T12:00:00+00:00 [queued]>
[2021-03-12 08:50:16,500] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-10T12:00:00+00:00 [queued]>
[2021-03-12 08:50:16,500] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 08:50:16,501] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-12 08:50:16,501] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 08:50:16,505] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): taskPrepare> on 2021-03-10T12:00:00+00:00
[2021-03-12 08:50:16,507] {standard_task_runner.py:52} INFO - Started process 143 to run task
[2021-03-12 08:50:16,509] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'conversion_flow', 'taskPrepare', '2021-03-10T12:00:00+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', '/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py', '--cfg-path', '/tmp/tmp4vk8poy_', '--error-file', '/tmp/tmpw5c24_kd']
[2021-03-12 08:50:16,510] {standard_task_runner.py:77} INFO - Job 2: Subtask taskPrepare
[2021-03-12 08:50:16,536] {logging_mixin.py:104} INFO - Running <TaskInstance: conversion_flow.taskPrepare 2021-03-10T12:00:00+00:00 [running]> on host ba9f3097ecdf
[2021-03-12 08:50:16,581] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=conversion_flow
AIRFLOW_CTX_TASK_ID=taskPrepare
AIRFLOW_CTX_EXECUTION_DATE=2021-03-10T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-10T12:00:00+00:00
[2021-03-12 08:50:16,581] {conversion_flow.py:73} ERROR - Error Occure in taskPrepare Task!
[2021-03-12 08:50:16,581] {conversion_flow.py:74} ERROR - 'NoneType' object has no attribute 'split'
[2021-03-12 08:50:16,581] {taskinstance.py:1455} ERROR - 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 75, in taskPrepare
    raise exception
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 29, in taskPrepare
    if sql_file_name.split(".")[1] != "sql":
AttributeError: 'NoneType' object has no attribute 'split'
[2021-03-12 08:50:16,582] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=conversion_flow, task_id=taskPrepare, execution_date=20210310T120000, start_date=20210312T085016, end_date=20210312T085016
[2021-03-12 08:50:16,602] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-03-12 10:54:49,328] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-10T12:00:00+00:00 [queued]>
[2021-03-12 10:54:49,336] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-10T12:00:00+00:00 [queued]>
[2021-03-12 10:54:49,336] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 10:54:49,336] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-12 10:54:49,336] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 10:54:49,340] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): taskPrepare> on 2021-03-10T12:00:00+00:00
[2021-03-12 10:54:49,342] {standard_task_runner.py:52} INFO - Started process 183 to run task
[2021-03-12 10:54:49,344] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'conversion_flow', 'taskPrepare', '2021-03-10T12:00:00+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', '/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py', '--cfg-path', '/tmp/tmp4da2gcgk', '--error-file', '/tmp/tmpkiojlj13']
[2021-03-12 10:54:49,345] {standard_task_runner.py:77} INFO - Job 2: Subtask taskPrepare
[2021-03-12 10:54:49,368] {logging_mixin.py:104} INFO - Running <TaskInstance: conversion_flow.taskPrepare 2021-03-10T12:00:00+00:00 [running]> on host 6299f34f884f
[2021-03-12 10:54:49,389] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=conversion_flow
AIRFLOW_CTX_TASK_ID=taskPrepare
AIRFLOW_CTX_EXECUTION_DATE=2021-03-10T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-10T12:00:00+00:00
[2021-03-12 10:54:49,389] {conversion_flow.py:73} ERROR - Error Occure in taskPrepare Task!
[2021-03-12 10:54:49,389] {conversion_flow.py:74} ERROR - 'NoneType' object has no attribute 'split'
[2021-03-12 10:54:49,390] {taskinstance.py:1455} ERROR - 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 75, in taskPrepare
    raise exception
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 29, in taskPrepare
    if sql_file_name.split(".")[1] != "sql":
AttributeError: 'NoneType' object has no attribute 'split'
[2021-03-12 10:54:49,391] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=conversion_flow, task_id=taskPrepare, execution_date=20210310T120000, start_date=20210312T105449, end_date=20210312T105449
[2021-03-12 10:54:49,435] {local_task_job.py:146} INFO - Task exited with return code 1
