[2021-03-12 08:07:11,108] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-12T08:07:09+00:00 [queued]>
[2021-03-12 08:07:11,117] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-12T08:07:09+00:00 [queued]>
[2021-03-12 08:07:11,117] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 08:07:11,117] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-12 08:07:11,117] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 08:07:11,122] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): taskPrepare> on 2021-03-12T08:07:09+00:00
[2021-03-12 08:07:11,124] {standard_task_runner.py:52} INFO - Started process 654 to run task
[2021-03-12 08:07:11,126] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'conversion_flow', 'taskPrepare', '2021-03-12T08:07:09+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', '/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py', '--cfg-path', '/tmp/tmp0cez1ap9', '--error-file', '/tmp/tmpq1vb7f0p']
[2021-03-12 08:07:11,127] {standard_task_runner.py:77} INFO - Job 36: Subtask taskPrepare
[2021-03-12 08:07:11,150] {logging_mixin.py:104} INFO - Running <TaskInstance: conversion_flow.taskPrepare 2021-03-12T08:07:09+00:00 [running]> on host 83c843b036e0
[2021-03-12 08:07:11,171] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=conversion_flow
AIRFLOW_CTX_TASK_ID=taskPrepare
AIRFLOW_CTX_EXECUTION_DATE=2021-03-12T08:07:09+00:00
AIRFLOW_CTX_DAG_RUN_ID=conversion_flow1615536429.201162
[2021-03-12 08:07:11,172] {conversion_flow.py:30} ERROR - Invalided MySQL backup file extension!
[2021-03-12 08:07:11,172] {conversion_flow.py:73} ERROR - Error Occure in taskPrepare Task!
[2021-03-12 08:07:11,172] {conversion_flow.py:74} ERROR - Invalided MySQL backup file extension!
[2021-03-12 08:07:11,172] {taskinstance.py:1455} ERROR - Invalided MySQL backup file extension!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 75, in taskPrepare
    raise exception
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 31, in taskPrepare
    raise ValueError('Invalided MySQL backup file extension!')
ValueError: Invalided MySQL backup file extension!
[2021-03-12 08:07:11,173] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=conversion_flow, task_id=taskPrepare, execution_date=20210312T080709, start_date=20210312T080711, end_date=20210312T080711
[2021-03-12 08:07:11,217] {local_task_job.py:146} INFO - Task exited with return code 1
