[2021-03-12 08:53:15,480] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-12T08:53:13+00:00 [queued]>
[2021-03-12 08:53:15,488] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-12T08:53:13+00:00 [queued]>
[2021-03-12 08:53:15,488] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 08:53:15,488] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-12 08:53:15,488] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 08:53:15,493] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): taskPrepare> on 2021-03-12T08:53:13+00:00
[2021-03-12 08:53:15,496] {standard_task_runner.py:52} INFO - Started process 819 to run task
[2021-03-12 08:53:15,498] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'conversion_flow', 'taskPrepare', '2021-03-12T08:53:13+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', '/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py', '--cfg-path', '/tmp/tmpccf9yrtc', '--error-file', '/tmp/tmpv58bap6j']
[2021-03-12 08:53:15,499] {standard_task_runner.py:77} INFO - Job 7: Subtask taskPrepare
[2021-03-12 08:53:15,519] {logging_mixin.py:104} INFO - Running <TaskInstance: conversion_flow.taskPrepare 2021-03-12T08:53:13+00:00 [running]> on host ba9f3097ecdf
[2021-03-12 08:53:15,539] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=conversion_flow
AIRFLOW_CTX_TASK_ID=taskPrepare
AIRFLOW_CTX_EXECUTION_DATE=2021-03-12T08:53:13+00:00
AIRFLOW_CTX_DAG_RUN_ID=conversion_flow1615539193.71727
[2021-03-12 08:53:15,540] {conversion_flow.py:30} ERROR - Invalided MySQL backup file extension!
[2021-03-12 08:53:15,540] {conversion_flow.py:73} ERROR - Error Occure in taskPrepare Task!
[2021-03-12 08:53:15,540] {conversion_flow.py:74} ERROR - Invalided MySQL backup file extension!
[2021-03-12 08:53:15,540] {taskinstance.py:1455} ERROR - Invalided MySQL backup file extension!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 75, in taskPrepare
    raise exception
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 31, in taskPrepare
    raise ValueError('Invalided MySQL backup file extension!')
ValueError: Invalided MySQL backup file extension!
[2021-03-12 08:53:15,541] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=conversion_flow, task_id=taskPrepare, execution_date=20210312T085313, start_date=20210312T085315, end_date=20210312T085315
[2021-03-12 08:53:15,590] {local_task_job.py:146} INFO - Task exited with return code 1
